# Feature Hunter Configuration
# Generated for CloudLab MTD testbed

# Network Configuration
network:
  # MTD shuffle interval in seconds
  shuffle_interval: 30
  
  # Attacker sniffing interface
  sniff_interface: "eth1"
  
  # Virtual IP pool (targets will be assigned from this pool)
  virtual_ips:
    - "10.10.1.20"
    - "10.10.1.21"
    - "10.10.1.22"
    - "10.10.1.23"
    - "10.10.1.24"
    - "10.10.1.25"
    - "10.10.1.26"
    - "10.10.1.27"
    - "10.10.1.28"
    - "10.10.1.29"
    - "10.10.1.30"
    - "10.10.1.31"
    - "10.10.1.32"
    - "10.10.1.33"
    - "10.10.1.34"
    - "10.10.1.35"
    - "10.10.1.36"
    - "10.10.1.37"
    - "10.10.1.38"
    - "10.10.1.39"
    - "10.10.1.40"
    - "10.10.1.41"
    - "10.10.1.42"
    - "10.10.1.43"
    - "10.10.1.44"
    - "10.10.1.45"
    - "10.10.1.46"
    - "10.10.1.47"
    - "10.10.1.48"
    - "10.10.1.49"
  
  # Real target IPs (from your MTD controller)
  real_targets:
    - "10.10.1.3"
    - "10.10.1.4" 
    - "10.10.1.5"
  
  # Server ports (iperf3 default + some extras)
  target_ports:
    - 5201  # iperf3 default
    - 5202  # iperf3 alt
    - 5203  # iperf3 alt
  
  # Attacker node
  attacker_ip: "10.10.1.2"

# Paths
paths:
  base_dir: "~/mtd-ai-security/features"
  runs_dir: "runs"
  capture_dir: "capture"
  features_dir: "features"
  experiments_dir: "experiments"
  reports_dir: "report"

# Traffic Generation
traffic:
  # HTTP client settings
  http:
    enabled: false  # Using iperf3 instead
    jitter_ms: [100, 500]  # Random delay range
    requests_per_minute: 60
  
  # Ping settings  
  ping:
    enabled: true
    interval_sec: 1
    jitter_ms: [50, 200]
  
  # iperf3 settings
  iperf3:
    enabled: true
    duration_sec: 10  # Per connection
    interval_sec: 5   # Between connections
    parallel_streams: 1

# Capture Settings
capture:
  # tcpdump ring buffer
  ring_buffer: true
  file_size_mb: 100
  file_count: 10
  
  # Packet filters
  bpf_filter: "host 10.10.1.0/24 and (tcp or udp)"
  
  # Capture duration alignment
  align_to_shuffle: true

# Feature Extraction
features:
  # Flow timeout (seconds)
  flow_timeout: 60
  
  # Features to extract
  extract:
    - "flow_duration"
    - "packet_count"  
    - "byte_count"
    - "bytes_per_packet"
    - "inter_arrival_times"
    - "tcp_flags"
    - "window_sizes"
    - "syn_ack_sizes"
    - "tls_features"
    - "rtt_estimates"

# Experiment Settings
experiments:
  # Random seed for reproducibility
  random_seed: 42
  
  # Cross-validation folds
  cv_folds: 5
  
  # Clustering
  clustering:
    k_range: [2, 3, 4, 5, 8, 10]
    dbscan_eps: [0.1, 0.3, 0.5]
    use_pca: true
    pca_components: 10
  
  # Autoencoder
  autoencoder:
    hidden_dims: [64, 32, 16, 32, 64]
    learning_rate: 0.001
    epochs: 100
    batch_size: 32
  
  # Contrastive Learning
  contrastive:
    embedding_dim: 128
    temperature: 0.1
    learning_rate: 0.001
    epochs: 200
    batch_size: 64
  
  # Time Series
  timeseries:
    sequence_length: 100
    cnn_filters: [64, 128, 256]
    transformer_heads: 8
    transformer_layers: 4
  
  # Feature Importance
  feature_importance:
    n_estimators: 100
    max_depth: 10
    
# Evaluation Metrics
evaluation:
  stability_threshold: 0.8
  uniqueness_threshold: 0.7
  clustering_metrics: ["ari", "nmi", "silhouette"]
  embedding_metrics: ["knn_accuracy", "center_distance"]

# Output Settings
output:
  save_intermediate: true
  generate_plots: true
  plot_format: "png"
  dpi: 300
